bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata21.list --out examples/extract_aitdatasets/aitdata21_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata22.list --out examples/extract_aitdatasets/aitdata22_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata23.list --out examples/extract_aitdatasets/aitdata23_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata24.list --out examples/extract_aitdatasets/aitdata24_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata25.list --out examples/extract_aitdatasets/aitdata25_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata26.list --out examples/extract_aitdatasets/aitdata26_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata27.list --out examples/extract_aitdatasets/aitdata27_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata28.list --out examples/extract_aitdatasets/aitdata28_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata29.list --out examples/extract_aitdatasets/aitdata29_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata30.list --out examples/extract_aitdatasets/aitdata30_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata31.list --out examples/extract_aitdatasets/aitdata31_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata32.list --out examples/extract_aitdatasets/aitdata32_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata33.list --out examples/extract_aitdatasets/aitdata33_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata34.list --out examples/extract_aitdatasets/aitdata34_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata35.list --out examples/extract_aitdatasets/aitdata35_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata36.list --out examples/extract_aitdatasets/aitdata36_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata37.list --out examples/extract_aitdatasets/aitdata37_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata38.list --out examples/extract_aitdatasets/aitdata38_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata39.list --out examples/extract_aitdatasets/aitdata39_annos.pkl
bash ./tools/dist_run.sh tools/data/custom_2d_skeleton.py 4 --video-list examples/extract_aitdatasets/datalists/aitdata40.list --out examples/extract_aitdatasets/aitdata40_annos.pkl