# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65tector.proto\x12\x08\x64\x65tector\"B\n\x0b\x41\x63tionClass\x12\x10\n\x08objectId\x18\x01 \x01(\x05\x12\x10\n\x08sourceId\x18\x02 \x01(\x05\x12\x0f\n\x07\x63lassId\x18\x03 \x01(\x05\"6\n\x0c\x41\x63tionResult\x12&\n\x07\x63lasses\x18\x01 \x03(\x0b\x32\x15.detector.ActionClass\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\">\n\tDetection\x12\x10\n\x08objectId\x18\x01 \x01(\x05\x12\x1f\n\x06points\x18\x02 \x03(\x0b\x32\x0f.detector.Point\"^\n\x10\x44\x65tectionResults\x12&\n\tdetection\x18\x01 \x03(\x0b\x32\x13.detector.Detection\x12\x10\n\x08\x66rameNum\x18\x02 \x01(\r\x12\x10\n\x08sourceId\x18\x03 \x01(\x05\"e\n\x15\x42\x61tchDetectionResults\x12\x33\n\x0f\x64\x65tectionResult\x18\x01 \x03(\x0b\x32\x1a.detector.DetectionResults\x12\x17\n\x0fprocess_time_ms\x18\x02 \x01(\x02\x32\x98\x01\n\x08\x44\x65tector\x12G\n\nDetectTest\x12\x1f.detector.BatchDetectionResults\x1a\x16.detector.ActionResult\"\x00\x12\x43\n\x06\x44\x65tect\x12\x1f.detector.BatchDetectionResults\x1a\x16.detector.ActionResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONCLASS._serialized_start=28
  _ACTIONCLASS._serialized_end=94
  _ACTIONRESULT._serialized_start=96
  _ACTIONRESULT._serialized_end=150
  _POINT._serialized_start=152
  _POINT._serialized_end=181
  _DETECTION._serialized_start=183
  _DETECTION._serialized_end=245
  _DETECTIONRESULTS._serialized_start=247
  _DETECTIONRESULTS._serialized_end=341
  _BATCHDETECTIONRESULTS._serialized_start=343
  _BATCHDETECTIONRESULTS._serialized_end=444
  _DETECTOR._serialized_start=447
  _DETECTOR._serialized_end=599
# @@protoc_insertion_point(module_scope)
