# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detector_pb2 as detector__pb2


class DetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectTest = channel.unary_unary(
                '/detector.Detector/DetectTest',
                request_serializer=detector__pb2.BatchDetectionResults.SerializeToString,
                response_deserializer=detector__pb2.ActionResult.FromString,
                )
        self.Detect = channel.unary_unary(
                '/detector.Detector/Detect',
                request_serializer=detector__pb2.BatchDetectionResults.SerializeToString,
                response_deserializer=detector__pb2.ActionResult.FromString,
                )


class DetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectTest': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectTest,
                    request_deserializer=detector__pb2.BatchDetectionResults.FromString,
                    response_serializer=detector__pb2.ActionResult.SerializeToString,
            ),
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=detector__pb2.BatchDetectionResults.FromString,
                    response_serializer=detector__pb2.ActionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detector.Detector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Detector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/detector.Detector/DetectTest',
            detector__pb2.BatchDetectionResults.SerializeToString,
            detector__pb2.ActionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/detector.Detector/Detect',
            detector__pb2.BatchDetectionResults.SerializeToString,
            detector__pb2.ActionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
